#!/usr/bin/python

import sys,os,png
import argparse


def main(argv):

	# Prologue
	print ";;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;"
	print "; spanRenderers"
	print ";"
	print "; Automatically generated by GenerateRenderSpans.py. Do not edit."
	print ";\nrenderSpamJumpTable:"

	for jump in range(0,80):
		print "\t.word renderSpan%d" % (jump+1)
	
	print "\n"

	for span in range(1,81):
		print "renderSpan%d:" % span

		bytes = "\t.byte "
		for byte in range(0,span-1):
			bytes += "$5a,"
		bytes += "$5a\n\tjmp renderSpanComplete\n"
		print bytes

if __name__ == "__main__":
	main(sys.argv[1:])
	
