;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;
; spanRenderers
;
; Automatically generated by GenerateRenderSpans.py. Do not edit.
;
renderSpanJumpTable:
	.word $0000
	.word renderSpan1
	.word renderSpan2
	.word renderSpan3
	.word renderSpan4
	.word renderSpan5
	.word renderSpan6
	.word renderSpan7
	.word renderSpan8
	.word renderSpan9
	.word renderSpan10
	.word renderSpan11
	.word renderSpan12
	.word renderSpan13
	.word renderSpan14
	.word renderSpan15
	.word renderSpan16
	.word renderSpan17
	.word renderSpan18
	.word renderSpan19
	.word renderSpan20
	.word renderSpan21
	.word renderSpan22
	.word renderSpan23
	.word renderSpan24
	.word renderSpan25
	.word renderSpan26
	.word renderSpan27
	.word renderSpan28
	.word renderSpan29
	.word renderSpan30
	.word renderSpan31
	.word renderSpan32
	.word renderSpan33
	.word renderSpan34
	.word renderSpan35
	.word renderSpan36
	.word renderSpan37
	.word renderSpan38
	.word renderSpan39
	.word renderSpan40
	.word renderSpan41
	.word renderSpan42
	.word renderSpan43
	.word renderSpan44
	.word renderSpan45
	.word renderSpan46
	.word renderSpan47
	.word renderSpan48
	.word renderSpan49
	.word renderSpan50
	.word renderSpan51
	.word renderSpan52
	.word renderSpan53
	.word renderSpan54
	.word renderSpan55
	.word renderSpan56
	.word renderSpan57
	.word renderSpan58
	.word renderSpan59
	.word renderSpan60
	.word renderSpan61
	.word renderSpan62
	.word renderSpan63
	.word renderSpan64
	.word renderSpan65
	.word renderSpan66
	.word renderSpan67
	.word renderSpan68
	.word renderSpan69
	.word renderSpan70
	.word renderSpan71
	.word renderSpan72
	.word renderSpan73
	.word renderSpan74
	.word renderSpan75
	.word renderSpan76
	.word renderSpan77
	.word renderSpan78
	.word renderSpan79
	.word renderSpan80


renderSpan1:
	ldx CURRMAPPIXELS
	.byte $da
	jmp renderSpanComplete

renderSpan2:
	ldx CURRMAPPIXELS
	.byte $da,$da
	jmp renderSpanComplete

renderSpan3:
	ldx CURRMAPPIXELS
	.byte $da,$da,$da
	jmp renderSpanComplete

renderSpan4:
	ldx CURRMAPPIXELS
	.byte $da,$da,$da,$da
	jmp renderSpanComplete

renderSpan5:
	ldx CURRMAPPIXELS
	.byte $da,$da,$da,$da,$da
	jmp renderSpanComplete

renderSpan6:
	ldx CURRMAPPIXELS
	.byte $da,$da,$da,$da,$da,$da
	jmp renderSpanComplete

renderSpan7:
	ldx CURRMAPPIXELS
	.byte $da,$da,$da,$da,$da,$da,$da
	jmp renderSpanComplete

renderSpan8:
	ldx CURRMAPPIXELS
	.byte $da,$da,$da,$da,$da,$da,$da,$da
	jmp renderSpanComplete

renderSpan9:
	ldx CURRMAPPIXELS
	.byte $da,$da,$da,$da,$da,$da,$da,$da,$da
	jmp renderSpanComplete

renderSpan10:
	ldx CURRMAPPIXELS
	.byte $da,$da,$da,$da,$da,$da,$da,$da,$da,$da
	jmp renderSpanComplete

renderSpan11:
	ldx CURRMAPPIXELS
	.byte $da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da
	jmp renderSpanComplete

renderSpan12:
	ldx CURRMAPPIXELS
	.byte $da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da
	jmp renderSpanComplete

renderSpan13:
	ldx CURRMAPPIXELS
	.byte $da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da
	jmp renderSpanComplete

renderSpan14:
	ldx CURRMAPPIXELS
	.byte $da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da
	jmp renderSpanComplete

renderSpan15:
	ldx CURRMAPPIXELS
	.byte $da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da
	jmp renderSpanComplete

renderSpan16:
	ldx CURRMAPPIXELS
	.byte $da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da
	jmp renderSpanComplete

renderSpan17:
	ldx CURRMAPPIXELS
	.byte $da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da
	jmp renderSpanComplete

renderSpan18:
	ldx CURRMAPPIXELS
	.byte $da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da
	jmp renderSpanComplete

renderSpan19:
	ldx CURRMAPPIXELS
	.byte $da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da
	jmp renderSpanComplete

renderSpan20:
	ldx CURRMAPPIXELS
	.byte $da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da
	jmp renderSpanComplete

renderSpan21:
	ldx CURRMAPPIXELS
	.byte $da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da
	jmp renderSpanComplete

renderSpan22:
	ldx CURRMAPPIXELS
	.byte $da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da
	jmp renderSpanComplete

renderSpan23:
	ldx CURRMAPPIXELS
	.byte $da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da
	jmp renderSpanComplete

renderSpan24:
	ldx CURRMAPPIXELS
	.byte $da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da
	jmp renderSpanComplete

renderSpan25:
	ldx CURRMAPPIXELS
	.byte $da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da
	jmp renderSpanComplete

renderSpan26:
	ldx CURRMAPPIXELS
	.byte $da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da
	jmp renderSpanComplete

renderSpan27:
	ldx CURRMAPPIXELS
	.byte $da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da
	jmp renderSpanComplete

renderSpan28:
	ldx CURRMAPPIXELS
	.byte $da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da
	jmp renderSpanComplete

renderSpan29:
	ldx CURRMAPPIXELS
	.byte $da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da
	jmp renderSpanComplete

renderSpan30:
	ldx CURRMAPPIXELS
	.byte $da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da
	jmp renderSpanComplete

renderSpan31:
	ldx CURRMAPPIXELS
	.byte $da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da
	jmp renderSpanComplete

renderSpan32:
	ldx CURRMAPPIXELS
	.byte $da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da
	jmp renderSpanComplete

renderSpan33:
	ldx CURRMAPPIXELS
	.byte $da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da
	jmp renderSpanComplete

renderSpan34:
	ldx CURRMAPPIXELS
	.byte $da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da
	jmp renderSpanComplete

renderSpan35:
	ldx CURRMAPPIXELS
	.byte $da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da
	jmp renderSpanComplete

renderSpan36:
	ldx CURRMAPPIXELS
	.byte $da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da
	jmp renderSpanComplete

renderSpan37:
	ldx CURRMAPPIXELS
	.byte $da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da
	jmp renderSpanComplete

renderSpan38:
	ldx CURRMAPPIXELS
	.byte $da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da
	jmp renderSpanComplete

renderSpan39:
	ldx CURRMAPPIXELS
	.byte $da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da
	jmp renderSpanComplete

renderSpan40:
	ldx CURRMAPPIXELS
	.byte $da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da
	jmp renderSpanComplete

renderSpan41:
	ldx CURRMAPPIXELS
	.byte $da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da
	jmp renderSpanComplete

renderSpan42:
	ldx CURRMAPPIXELS
	.byte $da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da
	jmp renderSpanComplete

renderSpan43:
	ldx CURRMAPPIXELS
	.byte $da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da
	jmp renderSpanComplete

renderSpan44:
	ldx CURRMAPPIXELS
	.byte $da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da
	jmp renderSpanComplete

renderSpan45:
	ldx CURRMAPPIXELS
	.byte $da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da
	jmp renderSpanComplete

renderSpan46:
	ldx CURRMAPPIXELS
	.byte $da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da
	jmp renderSpanComplete

renderSpan47:
	ldx CURRMAPPIXELS
	.byte $da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da
	jmp renderSpanComplete

renderSpan48:
	ldx CURRMAPPIXELS
	.byte $da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da
	jmp renderSpanComplete

renderSpan49:
	ldx CURRMAPPIXELS
	.byte $da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da
	jmp renderSpanComplete

renderSpan50:
	ldx CURRMAPPIXELS
	.byte $da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da
	jmp renderSpanComplete

renderSpan51:
	ldx CURRMAPPIXELS
	.byte $da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da
	jmp renderSpanComplete

renderSpan52:
	ldx CURRMAPPIXELS
	.byte $da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da
	jmp renderSpanComplete

renderSpan53:
	ldx CURRMAPPIXELS
	.byte $da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da
	jmp renderSpanComplete

renderSpan54:
	ldx CURRMAPPIXELS
	.byte $da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da
	jmp renderSpanComplete

renderSpan55:
	ldx CURRMAPPIXELS
	.byte $da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da
	jmp renderSpanComplete

renderSpan56:
	ldx CURRMAPPIXELS
	.byte $da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da
	jmp renderSpanComplete

renderSpan57:
	ldx CURRMAPPIXELS
	.byte $da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da
	jmp renderSpanComplete

renderSpan58:
	ldx CURRMAPPIXELS
	.byte $da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da
	jmp renderSpanComplete

renderSpan59:
	ldx CURRMAPPIXELS
	.byte $da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da
	jmp renderSpanComplete

renderSpan60:
	ldx CURRMAPPIXELS
	.byte $da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da
	jmp renderSpanComplete

renderSpan61:
	ldx CURRMAPPIXELS
	.byte $da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da
	jmp renderSpanComplete

renderSpan62:
	ldx CURRMAPPIXELS
	.byte $da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da
	jmp renderSpanComplete

renderSpan63:
	ldx CURRMAPPIXELS
	.byte $da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da
	jmp renderSpanComplete

renderSpan64:
	ldx CURRMAPPIXELS
	.byte $da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da
	jmp renderSpanComplete

renderSpan65:
	ldx CURRMAPPIXELS
	.byte $da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da
	jmp renderSpanComplete

renderSpan66:
	ldx CURRMAPPIXELS
	.byte $da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da
	jmp renderSpanComplete

renderSpan67:
	ldx CURRMAPPIXELS
	.byte $da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da
	jmp renderSpanComplete

renderSpan68:
	ldx CURRMAPPIXELS
	.byte $da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da
	jmp renderSpanComplete

renderSpan69:
	ldx CURRMAPPIXELS
	.byte $da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da
	jmp renderSpanComplete

renderSpan70:
	ldx CURRMAPPIXELS
	.byte $da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da
	jmp renderSpanComplete

renderSpan71:
	ldx CURRMAPPIXELS
	.byte $da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da
	jmp renderSpanComplete

renderSpan72:
	ldx CURRMAPPIXELS
	.byte $da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da
	jmp renderSpanComplete

renderSpan73:
	ldx CURRMAPPIXELS
	.byte $da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da
	jmp renderSpanComplete

renderSpan74:
	ldx CURRMAPPIXELS
	.byte $da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da
	jmp renderSpanComplete

renderSpan75:
	ldx CURRMAPPIXELS
	.byte $da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da
	jmp renderSpanComplete

renderSpan76:
	ldx CURRMAPPIXELS
	.byte $da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da
	jmp renderSpanComplete

renderSpan77:
	ldx CURRMAPPIXELS
	.byte $da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da
	jmp renderSpanComplete

renderSpan78:
	ldx CURRMAPPIXELS
	.byte $da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da
	jmp renderSpanComplete

renderSpan79:
	ldx CURRMAPPIXELS
	.byte $da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da
	jmp renderSpanComplete

renderSpan80:
	ldx CURRMAPPIXELS
	.byte $da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da
	jmp renderSpanComplete

;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;
; spanRenderersAlt
;
; Automatically generated by GenerateRenderSpans.py. Do not edit.
;
renderSpanJumpTableAlt:
	.word $0000
	.word renderSpanAlt1
	.word renderSpanAlt2
	.word renderSpanAlt3
	.word renderSpanAlt4
	.word renderSpanAlt5
	.word renderSpanAlt6
	.word renderSpanAlt7
	.word renderSpanAlt8
	.word renderSpanAlt9
	.word renderSpanAlt10
	.word renderSpanAlt11
	.word renderSpanAlt12
	.word renderSpanAlt13
	.word renderSpanAlt14
	.word renderSpanAlt15
	.word renderSpanAlt16
	.word renderSpanAlt17
	.word renderSpanAlt18
	.word renderSpanAlt19
	.word renderSpanAlt20
	.word renderSpanAlt21
	.word renderSpanAlt22
	.word renderSpanAlt23
	.word renderSpanAlt24
	.word renderSpanAlt25
	.word renderSpanAlt26
	.word renderSpanAlt27
	.word renderSpanAlt28
	.word renderSpanAlt29
	.word renderSpanAlt30
	.word renderSpanAlt31
	.word renderSpanAlt32
	.word renderSpanAlt33
	.word renderSpanAlt34
	.word renderSpanAlt35
	.word renderSpanAlt36
	.word renderSpanAlt37
	.word renderSpanAlt38
	.word renderSpanAlt39
	.word renderSpanAlt40
	.word renderSpanAlt41
	.word renderSpanAlt42
	.word renderSpanAlt43
	.word renderSpanAlt44
	.word renderSpanAlt45
	.word renderSpanAlt46
	.word renderSpanAlt47
	.word renderSpanAlt48
	.word renderSpanAlt49
	.word renderSpanAlt50
	.word renderSpanAlt51
	.word renderSpanAlt52
	.word renderSpanAlt53
	.word renderSpanAlt54
	.word renderSpanAlt55
	.word renderSpanAlt56
	.word renderSpanAlt57
	.word renderSpanAlt58
	.word renderSpanAlt59
	.word renderSpanAlt60
	.word renderSpanAlt61
	.word renderSpanAlt62
	.word renderSpanAlt63
	.word renderSpanAlt64
	.word renderSpanAlt65
	.word renderSpanAlt66
	.word renderSpanAlt67
	.word renderSpanAlt68
	.word renderSpanAlt69
	.word renderSpanAlt70
	.word renderSpanAlt71
	.word renderSpanAlt72
	.word renderSpanAlt73
	.word renderSpanAlt74
	.word renderSpanAlt75
	.word renderSpanAlt76
	.word renderSpanAlt77
	.word renderSpanAlt78
	.word renderSpanAlt79
	.word renderSpanAlt80


renderSpanAlt1:
	ldx CURRMAPPIXELS
	.byte $da
	jmp renderSpanCompleteAlt

renderSpanAlt2:
	ldx CURRMAPPIXELS
	.byte $da,$da
	jmp renderSpanCompleteAlt

renderSpanAlt3:
	ldx CURRMAPPIXELS
	.byte $da,$da,$da
	jmp renderSpanCompleteAlt

renderSpanAlt4:
	ldx CURRMAPPIXELS
	.byte $da,$da,$da,$da
	jmp renderSpanCompleteAlt

renderSpanAlt5:
	ldx CURRMAPPIXELS
	.byte $da,$da,$da,$da,$da
	jmp renderSpanCompleteAlt

renderSpanAlt6:
	ldx CURRMAPPIXELS
	.byte $da,$da,$da,$da,$da,$da
	jmp renderSpanCompleteAlt

renderSpanAlt7:
	ldx CURRMAPPIXELS
	.byte $da,$da,$da,$da,$da,$da,$da
	jmp renderSpanCompleteAlt

renderSpanAlt8:
	ldx CURRMAPPIXELS
	.byte $da,$da,$da,$da,$da,$da,$da,$da
	jmp renderSpanCompleteAlt

renderSpanAlt9:
	ldx CURRMAPPIXELS
	.byte $da,$da,$da,$da,$da,$da,$da,$da,$da
	jmp renderSpanCompleteAlt

renderSpanAlt10:
	ldx CURRMAPPIXELS
	.byte $da,$da,$da,$da,$da,$da,$da,$da,$da,$da
	jmp renderSpanCompleteAlt

renderSpanAlt11:
	ldx CURRMAPPIXELS
	.byte $da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da
	jmp renderSpanCompleteAlt

renderSpanAlt12:
	ldx CURRMAPPIXELS
	.byte $da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da
	jmp renderSpanCompleteAlt

renderSpanAlt13:
	ldx CURRMAPPIXELS
	.byte $da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da
	jmp renderSpanCompleteAlt

renderSpanAlt14:
	ldx CURRMAPPIXELS
	.byte $da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da
	jmp renderSpanCompleteAlt

renderSpanAlt15:
	ldx CURRMAPPIXELS
	.byte $da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da
	jmp renderSpanCompleteAlt

renderSpanAlt16:
	ldx CURRMAPPIXELS
	.byte $da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da
	jmp renderSpanCompleteAlt

renderSpanAlt17:
	ldx CURRMAPPIXELS
	.byte $da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da
	jmp renderSpanCompleteAlt

renderSpanAlt18:
	ldx CURRMAPPIXELS
	.byte $da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da
	jmp renderSpanCompleteAlt

renderSpanAlt19:
	ldx CURRMAPPIXELS
	.byte $da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da
	jmp renderSpanCompleteAlt

renderSpanAlt20:
	ldx CURRMAPPIXELS
	.byte $da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da
	jmp renderSpanCompleteAlt

renderSpanAlt21:
	ldx CURRMAPPIXELS
	.byte $da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da
	jmp renderSpanCompleteAlt

renderSpanAlt22:
	ldx CURRMAPPIXELS
	.byte $da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da
	jmp renderSpanCompleteAlt

renderSpanAlt23:
	ldx CURRMAPPIXELS
	.byte $da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da
	jmp renderSpanCompleteAlt

renderSpanAlt24:
	ldx CURRMAPPIXELS
	.byte $da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da
	jmp renderSpanCompleteAlt

renderSpanAlt25:
	ldx CURRMAPPIXELS
	.byte $da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da
	jmp renderSpanCompleteAlt

renderSpanAlt26:
	ldx CURRMAPPIXELS
	.byte $da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da
	jmp renderSpanCompleteAlt

renderSpanAlt27:
	ldx CURRMAPPIXELS
	.byte $da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da
	jmp renderSpanCompleteAlt

renderSpanAlt28:
	ldx CURRMAPPIXELS
	.byte $da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da
	jmp renderSpanCompleteAlt

renderSpanAlt29:
	ldx CURRMAPPIXELS
	.byte $da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da
	jmp renderSpanCompleteAlt

renderSpanAlt30:
	ldx CURRMAPPIXELS
	.byte $da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da
	jmp renderSpanCompleteAlt

renderSpanAlt31:
	ldx CURRMAPPIXELS
	.byte $da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da
	jmp renderSpanCompleteAlt

renderSpanAlt32:
	ldx CURRMAPPIXELS
	.byte $da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da
	jmp renderSpanCompleteAlt

renderSpanAlt33:
	ldx CURRMAPPIXELS
	.byte $da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da
	jmp renderSpanCompleteAlt

renderSpanAlt34:
	ldx CURRMAPPIXELS
	.byte $da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da
	jmp renderSpanCompleteAlt

renderSpanAlt35:
	ldx CURRMAPPIXELS
	.byte $da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da
	jmp renderSpanCompleteAlt

renderSpanAlt36:
	ldx CURRMAPPIXELS
	.byte $da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da
	jmp renderSpanCompleteAlt

renderSpanAlt37:
	ldx CURRMAPPIXELS
	.byte $da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da
	jmp renderSpanCompleteAlt

renderSpanAlt38:
	ldx CURRMAPPIXELS
	.byte $da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da
	jmp renderSpanCompleteAlt

renderSpanAlt39:
	ldx CURRMAPPIXELS
	.byte $da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da
	jmp renderSpanCompleteAlt

renderSpanAlt40:
	ldx CURRMAPPIXELS
	.byte $da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da
	jmp renderSpanCompleteAlt

renderSpanAlt41:
	ldx CURRMAPPIXELS
	.byte $da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da
	jmp renderSpanCompleteAlt

renderSpanAlt42:
	ldx CURRMAPPIXELS
	.byte $da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da
	jmp renderSpanCompleteAlt

renderSpanAlt43:
	ldx CURRMAPPIXELS
	.byte $da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da
	jmp renderSpanCompleteAlt

renderSpanAlt44:
	ldx CURRMAPPIXELS
	.byte $da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da
	jmp renderSpanCompleteAlt

renderSpanAlt45:
	ldx CURRMAPPIXELS
	.byte $da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da
	jmp renderSpanCompleteAlt

renderSpanAlt46:
	ldx CURRMAPPIXELS
	.byte $da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da
	jmp renderSpanCompleteAlt

renderSpanAlt47:
	ldx CURRMAPPIXELS
	.byte $da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da
	jmp renderSpanCompleteAlt

renderSpanAlt48:
	ldx CURRMAPPIXELS
	.byte $da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da
	jmp renderSpanCompleteAlt

renderSpanAlt49:
	ldx CURRMAPPIXELS
	.byte $da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da
	jmp renderSpanCompleteAlt

renderSpanAlt50:
	ldx CURRMAPPIXELS
	.byte $da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da
	jmp renderSpanCompleteAlt

renderSpanAlt51:
	ldx CURRMAPPIXELS
	.byte $da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da
	jmp renderSpanCompleteAlt

renderSpanAlt52:
	ldx CURRMAPPIXELS
	.byte $da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da
	jmp renderSpanCompleteAlt

renderSpanAlt53:
	ldx CURRMAPPIXELS
	.byte $da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da
	jmp renderSpanCompleteAlt

renderSpanAlt54:
	ldx CURRMAPPIXELS
	.byte $da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da
	jmp renderSpanCompleteAlt

renderSpanAlt55:
	ldx CURRMAPPIXELS
	.byte $da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da
	jmp renderSpanCompleteAlt

renderSpanAlt56:
	ldx CURRMAPPIXELS
	.byte $da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da
	jmp renderSpanCompleteAlt

renderSpanAlt57:
	ldx CURRMAPPIXELS
	.byte $da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da
	jmp renderSpanCompleteAlt

renderSpanAlt58:
	ldx CURRMAPPIXELS
	.byte $da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da
	jmp renderSpanCompleteAlt

renderSpanAlt59:
	ldx CURRMAPPIXELS
	.byte $da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da
	jmp renderSpanCompleteAlt

renderSpanAlt60:
	ldx CURRMAPPIXELS
	.byte $da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da
	jmp renderSpanCompleteAlt

renderSpanAlt61:
	ldx CURRMAPPIXELS
	.byte $da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da
	jmp renderSpanCompleteAlt

renderSpanAlt62:
	ldx CURRMAPPIXELS
	.byte $da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da
	jmp renderSpanCompleteAlt

renderSpanAlt63:
	ldx CURRMAPPIXELS
	.byte $da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da
	jmp renderSpanCompleteAlt

renderSpanAlt64:
	ldx CURRMAPPIXELS
	.byte $da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da
	jmp renderSpanCompleteAlt

renderSpanAlt65:
	ldx CURRMAPPIXELS
	.byte $da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da
	jmp renderSpanCompleteAlt

renderSpanAlt66:
	ldx CURRMAPPIXELS
	.byte $da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da
	jmp renderSpanCompleteAlt

renderSpanAlt67:
	ldx CURRMAPPIXELS
	.byte $da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da
	jmp renderSpanCompleteAlt

renderSpanAlt68:
	ldx CURRMAPPIXELS
	.byte $da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da
	jmp renderSpanCompleteAlt

renderSpanAlt69:
	ldx CURRMAPPIXELS
	.byte $da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da
	jmp renderSpanCompleteAlt

renderSpanAlt70:
	ldx CURRMAPPIXELS
	.byte $da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da
	jmp renderSpanCompleteAlt

renderSpanAlt71:
	ldx CURRMAPPIXELS
	.byte $da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da
	jmp renderSpanCompleteAlt

renderSpanAlt72:
	ldx CURRMAPPIXELS
	.byte $da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da
	jmp renderSpanCompleteAlt

renderSpanAlt73:
	ldx CURRMAPPIXELS
	.byte $da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da
	jmp renderSpanCompleteAlt

renderSpanAlt74:
	ldx CURRMAPPIXELS
	.byte $da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da
	jmp renderSpanCompleteAlt

renderSpanAlt75:
	ldx CURRMAPPIXELS
	.byte $da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da
	jmp renderSpanCompleteAlt

renderSpanAlt76:
	ldx CURRMAPPIXELS
	.byte $da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da
	jmp renderSpanCompleteAlt

renderSpanAlt77:
	ldx CURRMAPPIXELS
	.byte $da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da
	jmp renderSpanCompleteAlt

renderSpanAlt78:
	ldx CURRMAPPIXELS
	.byte $da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da
	jmp renderSpanCompleteAlt

renderSpanAlt79:
	ldx CURRMAPPIXELS
	.byte $da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da
	jmp renderSpanCompleteAlt

renderSpanAlt80:
	ldx CURRMAPPIXELS
	.byte $da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da,$da
	jmp renderSpanCompleteAlt

