; Autogenerated by Mr. Sprite. Do not modify


DrawSpriteBank :
 	 ASL 	  	 ; A=Sprite Number ($0000-$002C)
	  	 TAX 	  	 ; Y=Target Screen Address ($2000-$9D00)
	  	 LDA 	 SpriteBankNum,X 	 ; Relative Sprite Number Table
	  	 JMP 	 (SpriteBankBank,X) 	 ; Bank Number Table
	  	  	  	 
SpriteBankNum :
 	 .dbyt 	 $0D00,$0900,$2000,$1800,$1A00,$1F00,$2600,$2400 	 
	  	 .dbyt 	 $1D00,$1E00,$2300,$2C00,$1100,$1500,$1600,$2500 	 
	  	 .dbyt 	 $2200,$2100,$1C00,$1B00,$0E00,$1200,$0600,$0000 	 
	  	 .dbyt 	 $0300,$0400,$1000,$1300,$0C00,$0B00,$0A00,$0700 	 
	  	 .dbyt 	 $0100,$0200,$0500,$0F00,$1400,$0800,$1900,$1700 	 
	  	 .dbyt 	 $2B00,$2A00,$2900,$2800,$2700 	 
	  	  	  	 
SpriteBankBank :
 	 .addr 	 SpriteBankBank00,SpriteBankBank00,SpriteBankBank00,SpriteBankBank00,SpriteBankBank00,SpriteBankBank00,SpriteBankBank00,SpriteBankBank00 	 
	  	 .addr 	 SpriteBankBank00,SpriteBankBank00,SpriteBankBank00,SpriteBankBank00,SpriteBankBank00,SpriteBankBank00,SpriteBankBank00,SpriteBankBank00 	 
	  	 .addr 	 SpriteBankBank00,SpriteBankBank00,SpriteBankBank00,SpriteBankBank00,SpriteBankBank00,SpriteBankBank00,SpriteBankBank00,SpriteBankBank00 	 
	  	 .addr 	 SpriteBankBank00,SpriteBankBank00,SpriteBankBank00,SpriteBankBank00,SpriteBankBank00,SpriteBankBank00,SpriteBankBank00,SpriteBankBank00 	 
	  	 .addr 	 SpriteBankBank00,SpriteBankBank00,SpriteBankBank00,SpriteBankBank00,SpriteBankBank00,SpriteBankBank00,SpriteBankBank00,SpriteBankBank00 	 
	  	 .addr 	 SpriteBankBank00,SpriteBankBank00,SpriteBankBank00,SpriteBankBank00,SpriteBankBank00 	 
	  	  	  	 
SpriteBankBank00 :
 	 JSL 	 $AA0000 	 
	  	 PHK 	  	 
	  	 PLB 	  	 
	  	 RTS 	  	 
	  	  	  	 
;---------- 	  	  	 
